### ISSUE TITLE
Aspect Ratioが常に1になるバグがありそうです

### ISSUE THREAD

**Issue by BlueEventHorizon** [daichikuwa0618/ClippingImageSample-iOS#1]
https://github.com/daichikuwa0618/ClippingImageSample-iOS/blob/1c525c169a4b5dd4bb7209d53c78847b43295728/ClippingImageSample/ViewController.swift#L71

おそらくtypoではないでしょうか？

**Comment by daichikuwa0618** [comment]
バグですね、、、

**Comment by daichikuwa0618** [comment]
バグですね、、、

ありがとうございます。修正しようと思いますー
